---

name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: >
          docker
          build
          --tag "local/${GITHUB_REPOSITORY}"
          --label "org.label-schema.build-date=$(date --rfc-3339=seconds)"
          --label "org.label-schema.vcs-ref=${GITHUB_SHA}"
          --label
          "org.label-schema.vcs-url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          ./src
      - name: Check html-proofer install
        run: |
          docker run \
            "local/${GITHUB_REPOSITORY}" \
            htmlproofer --version
      - name: Create a docker tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag \
            "local/${GITHUB_REPOSITORY}" \
            "lvjp/html-proofer:${GITHUB_REF/refs\/tags\//}"
      - name: Prepare action.yaml with local docker image
        run: >
          sed -i -e "s@image:.*@image: local/${GITHUB_REPOSITORY}@" action.yml
      - name: Run regression tests
        uses: ./
        with:
          path: ./tests
          internal_domains: example.com
      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Docker hub
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker push "lvjp/html-proofer:${GITHUB_REF/refs\/tags\//}"
