name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Build image
        run: |
          docker build \
            --tag "local/${GITHUB_REPOSITORY}" \
            --label "org.label-schema.build-date=$(date --rfc-3339=seconds)" \
            --label "org.label-schema.vcs-ref=${GITHUB_SHA}" \
            --label "org.label-schema.vcs-url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            ./src
      - name: Check html-proofer install
        run: |
          docker run \
            "local/${GITHUB_REPOSITORY}" \
            htmlproofer --version
      - name: Create a docker tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag \
            "local/${GITHUB_REPOSITORY}" \
            "lvjp/html-proofer:${GITHUB_REF/refs\/tags\//}"
      - name: Run regression tests
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ./
        with:
          path: ./tests
      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Docker hub
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker push "lvjp/html-proofer:${GITHUB_REF/refs\/tags\//}"
