name: Build

on: push

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Regressions tests
        uses: ./
        with:
          path: ./tests
